mirtCAT Vignette Files
=====================

The following contains a list of links to various HTML vignettes with the `mirtCAT` package, 
generated using R markdown via the `knitr` package and hosted on Github.  

## Generating GUI Examples

- [Simple Survey](http://philchalmers.github.io/mirtCAT/html/simple_survey.html). Define a survey
  with only 3 Likert-type items, without any scoring/CAT definitions
- [Unidimensional CAT](http://philchalmers.github.io/mirtCAT/html/unidim-exampleGUI.html). A unidimensional CAT session using Maximum Information as the selction
  criteria with EAP estimation 
- [Customizing a small number of GUI elements](http://philchalmers.github.io/mirtCAT/html/customizeGUI.html). Customize elements such as the title page, authors list, last page, include graphical
  item stems, etc, and include a pre-CAT section to collect information prior to beginning the CAT 
- [MCAT example](http://philchalmers.github.io/mirtCAT/html/multidim-exampleGUI.html). Define two factor
 MCAT using Drule selection and terminating when $SE(\hat{\theta}) < .3$ OR 50 items have been 
 administered

## Offline Examples (no GUI)

- [Define population IRT parameters](http://philchalmers.github.io/mirtCAT/html/run-offline.html).
  Run a simple offline unidimensional CAT using predefined CAT parameters
- [MCAT example](http://philchalmers.github.io/mirtCAT/html/multidim-example.html). Run a 
  multidimensional CAT using predefined CAT parameters with dichotomous data
- [MCAT example with graded response model](http://philchalmers.github.io/mirtCAT/html/run-offline-graded.html). Run with Kullback-Leiber information and ML estimation

### User contributions

If you would like to contribute your own to the collection then feel free to send along your 
source file (`.Rmd`) to `rphilip.chalmers@gmail.com` and I'll add it to the appropriate package 
locations on Github. 
