Unidimensional Example
======================================

This example demonstrates how a unidimensional IRT test can be scored and modified for offline 
and online use. 

The following codeblock defines 100 items for a math test measuring addition skills.

```{r}
library('mirtCAT')

# define population IRT parameters
set.seed(1234)
nitems <- 100
itemnames <- paste0('Item.', 1:nitems)
a <- matrix(rlnorm(nitems, .2, .3))
d <- matrix(rnorm(nitems))

# create dummy dataset
dat <- matrix(c(1,0), 2, nitems)
colnames(dat) <- itemnames

# use population values for model
sv <- mirt(dat, 1, pars = 'values')
sv$value[sv$name == 'a1'] <- a[,1]
sv$value[sv$name == 'd'] <- d[,1]
sv$value[sv$name == 'g'] <- 0.2
mod <- mirt(dat, 1, pars = sv, TOL = NaN)

# math items definitions
# addition for one factor and multiplication for the other
shiny_questions <- questions <- vector('list', nitems)
names(shiny_questions) <- names(questions) <- itemnames
answers <- character(nitems)
choices <- vector('list', nitems)
spacing <- floor(d - min(d)) + 1 #easier items have more variation

for(i in 1:nitems){
    n1 <- sample(1:100, 1)
    n2 <- sample(101:200, 1)
    ans <- n1 + n2
    questions[[i]] <- paste0(n1, ' + ', n2, ' = ?')
    answers[i] <- as.character(ans)
    ch <- ans + sample(c(-5:-1, 1:5) * spacing[i,], 5)
    ch[sample(1:5, 1)] <- ans
    choices[[i]] <- as.character(ch)
}

# load list of items and their answers
for(i in 1L:nitems){
    shiny_questions[[i]] <- radioButtons(inputId = itemnames[i],
                                         label = questions[[i]],
                                         choices = choices[[i]])
}
```

Run the GUI using maximum-information selection, ML estimation, 
and stopping when $SE(\hat{\theta}) < 0.3$.

```{r, eval=FALSE}
result <- mirtCAT(shiny_questions, mod, item_answers = answers, method = 'ML', criteria = 'MI', 
                  design = list(min_SEM = 0.3))
print(result)
plot(result)
```