seedResponses <- function(x, items, responses, updateTheta = TRUE){
    if(missing(x) || missing(items) || missing(responses))
        stop('require inputs have not been supplied', call.=FALSE)
    if(!is.vector(responses) || !is.vector(items))
        stop("responses and items must be vectors")
    if(any(items > length(x$person$responses)))
        stop('One of the items locations is larger than the length of the test.', call.=FALSE)
    if(any(x$person$items_answered %in% items))
        stop('One of the selected items has already been administered', call.=FALSE)
    x$person$responses[items] <- as.integer(responses)
    x$person$raw_responses[items] <- as.character(x$person$responses[items] + 1L)
    pick <- min(which(is.na(x$person$items_answered)))
    x$person$items_answered[pick:(length(responses)+pick-1L)] <- as.integer(items)
    if(updateTheta)
        x$design@Update.thetas(x$design, x$person, x$test) 
    x$person$Update.info_mats(design=x$design, test=x$test)
    x$design <- Update.stop_now(x$design, x$person)
    return(x)
}
